import{i as l,S as p}from"./assets/vendor-B2mb6eXk.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();function u(s){const e="https://pixabay.com/api/",i=new URLSearchParams({key:"44946850-4c776fe0ffa968f959f660738",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${e}?${i}`).then(a=>{if(!a.ok)throw new Error(a.status);return a.json()}).then(a=>{if(a.hits.length===0)throw new Error("No images found");return a})}function d(s){return s.map(e=>`<li class="gallery-list">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}">
        </a>
        <div >
          <ul class="text-list">
            <li class="text-item"><p class="text"><span class="text-span">Likes</span><span class="link-span">${e.likes}</span></p></li>
            <li class="text-item"><p class="text"><span class="text-span">Views</span><span class="link-span">${e.views}</span></p></li>
            <li class="text-item"><p class="text"><span class="text-span">Comments</span><span class="link-span">${e.comments}</span></p></li>
            <li class="text-item"><p class="text"><span class="text-span">Downloads</span><span class="link-span">${e.downloads}</span></p></li>
          </ul>
        </div>
      </li>`).join("")}const n={form:document.querySelector(".form"),btnSearch:document.querySelector(".btn-search"),imgList:document.querySelector(".gallery"),loader:document.querySelector(".loader")};let c;n.form.addEventListener("submit",s=>{s.preventDefault();const e=s.target.elements.text.value.trim();if(!e){l.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}n.loader.classList.remove("loader--hidden"),n.imgList.innerHTML="",u(e).then(i=>{if(i.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}n.imgList.innerHTML=d(i.hits),c?c.refresh():c=new p(".gallery-link",{captionsData:"alt",captionDelay:250})}).catch(i=>{l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),console.error("Fetch error: ",i)}).finally(()=>{n.loader.classList.add("loader--hidden")}),s.currentTarget.reset()});window.addEventListener("load",()=>{document.querySelector(".loader").classList.add("loader--hidden")});
//# sourceMappingURL=index.js.map
